# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
