# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170806_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='created',
            new_name='date_joined',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates that this user account should be considered active. Users marked as inactive cannot login.'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates that this user can access the admin site.'),
        ),
    ]
