# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170806_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
