# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 23:53
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_myuser_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date of check-in.')),
                ('status', models.CharField(blank=True, choices=[('C', 'Completed'), ('U', 'Unreachable'), ('M', 'Left Message')], help_text='Current status of check-in.', max_length=1, null=True)),
                ('mode', models.CharField(blank=True, choices=[('P', 'Phone'), ('V', 'Visit'), ('I', 'In-Person')], help_text='Mode of communication for check-in', max_length=1, null=True)),
                ('notify_school_admin', models.BooleanField(default=False, help_text='Should school administration be notified')),
                ('success_score', models.PositiveIntegerField(default=1, help_text='Scale (1-10) of check-in success', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('info_learned', models.TextField(blank=True, help_text='Most important thing you learned about your mentee at your most recent mentoring check-in.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('student_id', models.CharField(help_text='School identifier for student.', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Designates that this student should be considered active.')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('language', models.CharField(help_text="Student/family's spoken language.", max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Contact email for student.', max_length=255, null=True)),
                ('grade', models.CharField(blank=True, choices=[('PK', 'Pre-Kindergarten'), ('K', 'Kindergarten'), ('1', '1st Grade'), ('2', '2nd Grade'), ('3', '3rd Grade'), ('4', '4th Grade'), ('5', '5th Grade'), ('6', '6th Grade'), ('7', '7th Grade'), ('8', '8th Grade'), ('9', '9th Grade'), ('10', '10th Grade'), ('11', '11th Grade'), ('12', '12th Grade'), ('O', 'Other')], help_text='Grade level of student.', max_length=2, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='full_name',
        ),
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='student',
            field=models.ForeignKey(help_text='Student that check-in is on behalf of.', on_delete=django.db.models.deletion.CASCADE, to='core.Student'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='teacher',
            field=models.ForeignKey(help_text='Person leading the check-in.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
