# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 00:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170806_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Designates that this Team should be considered active.')),
                ('state', models.CharField(blank=True, help_text='State where District/University is headquartered.', max_length=2, null=True)),
                ('email_contact', models.EmailField(help_text='Email for District/University contact.', max_length=255)),
                ('is_charter', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Designates that this Team should be considered active.')),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.District')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Designates that this Team should be considered active.')),
                ('description', models.TextField(blank=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.District')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='checkin',
            name='info_better',
            field=models.TextField(blank=True, help_text='What could have made this mentor check-in better?', null=True, verbose_name='Improvements for Future'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='info_learned',
            field=models.TextField(blank=True, help_text='Most important thing you learned about your mentee at your most recent mentoring check-in.', null=True, verbose_name='Information Gathered'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='mode',
            field=models.CharField(blank=True, choices=[('P', 'Phone'), ('V', 'Visit'), ('I', 'In-Person')], help_text='Mode of communication for check-in.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='notify_school_admin',
            field=models.BooleanField(default=False, help_text='Should school administrator be notified?'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='success_score',
            field=models.PositiveIntegerField(default=1, help_text='Scale (1-10) of check-in success.', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='myuser',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.District'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='school',
            field=models.ManyToManyField(blank=True, related_name='members', to='core.School'),
        ),
        migrations.AddField(
            model_name='student',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.District'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.School'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
            preserve_default=False,
        ),
    ]
