# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170807_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='members', to='core.Team'),
        ),
    ]
