# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_myuser_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.School'),
            preserve_default=False,
        ),
    ]
