# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_team_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
