# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 00:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_myuser_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='district',
        ),
        migrations.RemoveField(
            model_name='team',
            name='school',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='team',
        ),
        migrations.RemoveField(
            model_name='student',
            name='team',
        ),
        migrations.AddField(
            model_name='myuser',
            name='grade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('T', 'Teacher'), ('SA', 'School Admin'), ('DA', 'District Admin')], default='T', help_text='Account Type', max_length=2),
        ),
        migrations.AddField(
            model_name='myuser',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
