# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170812_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='school',
        ),
        migrations.AddField(
            model_name='myuser',
            name='school',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.School'),
            preserve_default=False,
        ),
    ]
