# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170812_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.School'),
        ),
    ]
