# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170812_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='custom_text_info_better',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='custom_text_info_learned',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='custom_text_succces_score',
            field=models.TextField(blank=True, null=True),
        ),
    ]
