# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170812_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='mode',
            field=models.CharField(choices=[('O', 'Other'), ('P', 'Phone'), ('V', 'Visit'), ('I', 'In-Person')], default='O', help_text='Mode of communication for check-in.', max_length=1),
        ),
    ]
