# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170812_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='mode',
            field=models.CharField(choices=[('P', 'Phone'), ('V', 'Visit'), ('I', 'In-Person')], help_text='Mode of communication for check-in.', max_length=1),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='status',
            field=models.CharField(choices=[('C', 'Completed'), ('U', 'Unreachable'), ('M', 'Left Message')], help_text='Current status of check-in.', max_length=1),
        ),
    ]
