# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 01:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20170813_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Date of check-in.'),
        ),
    ]
