# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20170813_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date of check-in.'),
        ),
    ]
