# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20170828_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='mode',
            field=models.CharField(choices=[('P', 'Phone'), ('V', 'Visit'), ('I', 'In-Person'), ('E', 'Email')], help_text='Mode of communication for check-in.', max_length=1),
        ),
    ]
