# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-08 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20170923_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='ednudge_district_id',
            field=models.CharField(blank=True, help_text='The EdNudge internal system-generated identifier for the district.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='ednudge_district_local_id',
            field=models.CharField(blank=True, help_text='The District Local Id.  This field is sourced from EdNudge.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='ednudge_is_enabled',
            field=models.BooleanField(default=False, help_text='Designates whether EdNudge integration is enabled for this district.'),
        ),
        migrations.AddField(
            model_name='school',
            name='ednudge_district_id',
            field=models.CharField(blank=True, help_text='The EdNudge internal system-generated identifier for the district.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='ednudge_is_enabled',
            field=models.BooleanField(default=False, help_text='Designates whether EdNudge integration is enabled for this district.'),
        ),
        migrations.AddField(
            model_name='school',
            name='ednudge_school_id',
            field=models.CharField(blank=True, help_text='The EdNudge internal system-generated identifier for the school.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='ednudge_school_local_id',
            field=models.CharField(blank=True, help_text='The School Local Id.  This field is sourced from EdNudge.', max_length=255, null=True),
        ),
    ]
