# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-14 20:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_ednudge_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('term_name', models.CharField(max_length=255)),
                ('term_start_date', models.DateField()),
                ('term_end_date', models.DateField()),
                ('period', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('ednudge_is_enabled', models.BooleanField(default=False, help_text='Designates whether EdNudge integration is enabled for this entity.')),
                ('ednudge_section_id', models.CharField(blank=True, help_text='The EdNudge internal system-generated identifier for the section.', max_length=255, null=True)),
                ('ednudge_section_local_id', models.CharField(blank=True, help_text='The Section Local Id.  This field is sourced from EdNudge.', max_length=255, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.District')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('ednudge_is_enabled', models.BooleanField(default=False, help_text='Designates whether EdNudge integration is enabled for this entity.')),
                ('ednudge_enrollment_id', models.CharField(blank=True, help_text='The EdNudge internal system-generated identifier for the enrollment.', max_length=255, null=True)),
                ('ednudge_section_id', models.CharField(blank=True, help_text='The EdNudge internal system-generated identifier for the section.', max_length=255, null=True)),
                ('ednudge_person_id', models.CharField(blank=True, help_text='The EdNudge internal system-generated identifier for the section.', max_length=255, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('ednudge_is_enabled', models.BooleanField(default=False, help_text='Designates whether EdNudge integration is enabled for this entity.')),
                ('ednudge_enrollment_id', models.CharField(blank=True, help_text='The EdNudge internal system-generated identifier for the enrollment.', max_length=255, null=True)),
                ('ednudge_section_id', models.CharField(blank=True, help_text='The EdNudge internal system-generated identifier for the section.', max_length=255, null=True)),
                ('ednudge_person_id', models.CharField(blank=True, help_text='The EdNudge internal system-generated identifier for the section.', max_length=255, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Section')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('core.myuser',),
        ),
        migrations.AlterField(
            model_name='school',
            name='ednudge_is_enabled',
            field=models.BooleanField(default=False, help_text='Designates whether EdNudge integration is enabled for this entity.'),
        ),
        migrations.AddField(
            model_name='sectionteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.School'),
        ),
        migrations.AddField(
            model_name='section',
            name='students',
            field=models.ManyToManyField(through='core.SectionStudent', to='core.Student'),
        ),
        migrations.AddField(
            model_name='section',
            name='teachers',
            field=models.ManyToManyField(through='core.SectionTeacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
