# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-14 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20190214_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='ednudge_is_enabled',
            field=models.BooleanField(default=False, help_text='Designates whether EdNudge integration is enabled.'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='ednudge_person_id',
            field=models.CharField(blank=True, help_text='The EdNudge internal system-generated identifier for the Person.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='ednudge_person_local_id',
            field=models.CharField(blank=True, help_text='The Person Local Id.  This field is sourced from EdNudge.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='ednudge_person_type',
            field=models.CharField(blank=True, help_text='The EdNudge Person Type.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ednudge_is_enabled',
            field=models.BooleanField(default=False, help_text='Designates whether EdNudge integration is enabled.'),
        ),
        migrations.AddField(
            model_name='student',
            name='ednudge_learner_id',
            field=models.CharField(blank=True, help_text='The EdNudge internal system-generated identifier for the learner.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ednudge_learner_local_id',
            field=models.CharField(blank=True, help_text='The Learner Local Id.  This field is sourced from EdNudge.', max_length=255, null=True),
        ),
    ]
