# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-14 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20190214_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='ednudge_district_id',
            field=models.CharField(blank=True, help_text='The EdNudge internal system-generated identifier for the district.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='ednudge_person_id',
            field=models.CharField(blank=True, help_text='The EdNudge internal system-generated identifier for the Person.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='ednudge_school_id',
            field=models.CharField(blank=True, help_text='The EdNudge internal system-generated identifier for the school.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='ednudge_section_id',
            field=models.CharField(blank=True, help_text='The EdNudge internal system-generated identifier for the section.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sectionstudent',
            name='ednudge_enrollment_id',
            field=models.CharField(blank=True, help_text='The EdNudge internal system-generated identifier for the enrollment.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sectionteacher',
            name='ednudge_enrollment_id',
            field=models.CharField(blank=True, help_text='The EdNudge internal system-generated identifier for the enrollment.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ednudge_learner_id',
            field=models.CharField(blank=True, help_text='The EdNudge internal system-generated identifier for the learner.', max_length=255, null=True, unique=True),
        ),
    ]
