# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-26 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20190214_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='ednudge_merkleroot',
            field=models.CharField(blank=True, editable=False, help_text='The EdNudge internal system-generated merkleroot.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='ednudge_merkleroot',
            field=models.CharField(blank=True, editable=False, help_text='The EdNudge internal system-generated merkleroot.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='ednudge_merkleroot',
            field=models.CharField(blank=True, editable=False, help_text='The EdNudge internal system-generated merkleroot.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='ednudge_merkleroot',
            field=models.CharField(blank=True, editable=False, help_text='The EdNudge internal system-generated merkleroot.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ednudge_merkleroot',
            field=models.CharField(blank=True, editable=False, help_text='The EdNudge internal system-generated merkleroot.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='ednudge_district_id',
            field=models.CharField(blank=True, editable=False, help_text='The EdNudge internal system-generated identifier for the district.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='ednudge_district_local_id',
            field=models.CharField(blank=True, editable=False, help_text='The District Local Id.  This field is sourced from EdNudge.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='ednudge_is_enabled',
            field=models.BooleanField(default=False, editable=False, help_text='Designates whether EdNudge integration is enabled for this district.'),
        ),
        migrations.AlterField(
            model_name='school',
            name='ednudge_district_id',
            field=models.CharField(blank=True, editable=False, help_text='The EdNudge internal system-generated identifier for the district.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='ednudge_is_enabled',
            field=models.BooleanField(default=False, editable=False, help_text='Designates whether EdNudge integration is enabled for this entity.'),
        ),
        migrations.AlterField(
            model_name='school',
            name='ednudge_school_id',
            field=models.CharField(blank=True, editable=False, help_text='The EdNudge internal system-generated identifier for the school.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='ednudge_school_local_id',
            field=models.CharField(blank=True, editable=False, help_text='The School Local Id.  This field is sourced from EdNudge.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ednudge_is_enabled',
            field=models.BooleanField(default=False, editable=False, help_text='Designates whether EdNudge integration is enabled.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ednudge_learner_id',
            field=models.CharField(blank=True, editable=False, help_text='The EdNudge internal system-generated identifier for the learner.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ednudge_learner_local_id',
            field=models.CharField(blank=True, editable=False, help_text='The Learner Local Id.  This field is sourced from EdNudge.', max_length=255, null=True),
        ),
    ]
