# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-28 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20190226_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionstudent',
            name='ednudge_merkleroot',
            field=models.CharField(blank=True, editable=False, help_text='The EdNudge internal system-generated merkleroot.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sectionteacher',
            name='ednudge_merkleroot',
            field=models.CharField(blank=True, editable=False, help_text='The EdNudge internal system-generated merkleroot.', max_length=255, null=True),
        ),
    ]
