# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-27 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20190228_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDailyAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date of attendance mark.')),
                ('mark', models.CharField(choices=[('a', 'absent'), ('t', 'tardy'), ('p', 'present')], help_text='Attendance Mark.', max_length=1)),
                ('ednudge_is_enabled', models.BooleanField(default=False, help_text='Designates whether EdNudge integration is enabled for this entity.')),
                ('ednudge_dailyattendance_id', models.CharField(blank=True, help_text='The EdNudge internal system-generated identifier for the dailyattendance.', max_length=255, null=True, unique=True)),
                ('ednudge_dailyattendance_local_id', models.CharField(blank=True, help_text='The dailyattendance Local Id.  This field is sourced from EdNudge.', max_length=255, null=True)),
                ('ednudge_merkleroot', models.CharField(blank=True, editable=False, help_text='The EdNudge internal system-generated merkleroot.', max_length=255, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.School')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
