# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-27 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_studentdailyattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_absences',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='Total number of absences since the beginning of the school year.', null=True),
        ),
    ]
