# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-07-08 17:12
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion
import versions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_soft_deletes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('identity', models.UUIDField()),
                ('version_start_date', models.DateTimeField()),
                ('version_end_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('version_birth_date', models.DateTimeField()),
                ('name', models.CharField(help_text='Name of the Strategy.  This should be globally unique so that you can identify this strategy as it changes over time.  The system does not enforce global uniqueness though.', max_length=255)),
                ('display_name', models.CharField(help_text='The Strategy name that is displayed on checkin forms.', max_length=255)),
                ('description', models.CharField(help_text='Expository text about the Strategy; used in page views to elaborate on the Strategy beyond what is in the display_name.', max_length=255)),
                ('grade_level_from', core.models.GradeLevelField(blank=True, choices=[('PK', 'Pre-Kindergarten'), ('K', 'Kindergarten'), ('1', '1st Grade'), ('2', '2nd Grade'), ('3', '3rd Grade'), ('4', '4th Grade'), ('5', '5th Grade'), ('6', '6th Grade'), ('7', '7th Grade'), ('8', '8th Grade'), ('9', '9th Grade'), ('10', '10th Grade'), ('11', '11th Grade'), ('12', '12th Grade'), ('O', 'Other')], help_text='Grade level of student.', max_length=2, null=True)),
                ('grade_level_to', core.models.GradeLevelField(blank=True, choices=[('PK', 'Pre-Kindergarten'), ('K', 'Kindergarten'), ('1', '1st Grade'), ('2', '2nd Grade'), ('3', '3rd Grade'), ('4', '4th Grade'), ('5', '5th Grade'), ('6', '6th Grade'), ('7', '7th Grade'), ('8', '8th Grade'), ('9', '9th Grade'), ('10', '10th Grade'), ('11', '11th Grade'), ('12', '12th Grade'), ('O', 'Other')], help_text='Grade level of student.', max_length=2, null=True)),
                ('is_tier1', models.BooleanField(default=False, help_text='True if Tier1 Strategy.')),
                ('is_tier2', models.BooleanField(default=False, help_text='True if Tier2 Strategy.')),
                ('is_tier3', models.BooleanField(default=False, help_text='True if Tier3 Strategy.')),
                ('district', models.ForeignKey(blank=True, help_text='If blank, the Strategy is Global and applies to all users.  If specified, the Strategy only applies to the specified district. Once an intervention strategy is created, you cannot change the district since that would have potential security implications.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.District')),
                ('practice', models.ForeignKey(help_text='The Practice this Strategy belongs to.', on_delete=django.db.models.deletion.CASCADE, to='core.Practice')),
            ],
            options={
                'verbose_name_plural': 'Strategies',
            },
        ),
        migrations.AddField(
            model_name='checkin',
            name='strategy_as_of',
            field=models.DateTimeField(blank=True, default=None, help_text='The date the strategy was changed.  This is used to render the correct version of the strategy.', null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='_strategy',
            field=versions.fields.VersionedForeignKey(blank=True, db_column='strategy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Strategy'),
        ),
    ]
