# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-08-13 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_library_framework_20190729_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='strategy_favorites',
            field=models.ManyToManyField(blank=True, to='core.Strategy'),
        ),
    ]
