# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-08-15 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_myuser_strategy_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='mode',
            field=models.CharField(choices=[('P', 'Phone'), ('V', 'Home Visit'), ('I', 'Conference'), ('E', 'Email')], help_text='Mode of communication for check-in.', max_length=1),
        ),
    ]
