# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-08-07 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_intervention_strategy_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='strategy_favorites',
            field=models.ManyToManyField(blank=True, null=True, to='core.Strategy'),
        ),
    ]
