# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-08-22 08:40
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.flatpages.models import FlatPage
from django.contrib.sites.models import Site
from django.db import connection
import os

def change_library_framework_url_into_strategy_framework(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    # db_name = os.getenv('DB_NAME')
    # if db_name != connection.settings_dict['NAME']:
    #     return
    try:
        site = Site.objects.get(pk=1)
    except Site.DoesNotExist:
        site = Site.objects.create(domain="app.allhere.co", name="allhere")
    
    try:
        flatpage = FlatPage.objects.get(url='/library/framework/')
        flatpage.registration_required = True
        flatpage.url='/strategy-framework/'
        flatpage.save()
    except FlatPage.DoesNotExist:
        flatpage = FlatPage.objects.create(
            url='/strategy-framework/',
            title="Strategy Framework",
            content="AllHere Strategy",
            registration_required=True,
        )
        flatpage.sites.add(site)
        flatpage.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20190815_1816'),
        ('sites', '0002_alter_domain_unique'),
        ('flatpages', '0001_initial'), 
    ]

    operations = [
        migrations.RunPython(change_library_framework_url_into_strategy_framework),
    ]
