# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-08-20 22:56
from __future__ import unicode_literals

from django.db import migrations
from core.models import CheckIn

def checkins_format_change_page(apps, schema_editor):
    CheckIn.objects.filter(mode='V').update(mode='H')
    CheckIn.objects.filter(mode='I').update(mode='C')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20190815_1816'),
    ]

    operations = [
        migrations.RunPython(checkins_format_change_page),
    ]