# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-08-30 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_change_library_framework_url_20190822_0440'),
    ]

    operations = [
    ]
