# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='schools',
            name='group',
        ),
        migrations.RenameField(
            model_name='userah',
            old_name='is_coach',
            new_name='is_leader',
        ),
        migrations.RenameField(
            model_name='userah',
            old_name='is_group_admin',
            new_name='is_manager',
        ),
        migrations.RemoveField(
            model_name='group',
            name='is_university',
        ),
        migrations.RemoveField(
            model_name='userah',
            name='hangout_email',
        ),
        migrations.AlterField(
            model_name='userah',
            name='is_teacher',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Schools',
        ),
        migrations.AddField(
            model_name='school',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group'),
        ),
    ]
