# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-05 16:49
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170804_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('absence', models.PositiveIntegerField(default=0)),
                ('tardies', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CheckIns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('C', 'Completed'), ('U', 'Unreachable'), ('M', 'Left Message')], max_length=1, null=True)),
                ('format', models.CharField(blank=True, choices=[('P', 'Phone'), ('V', 'Visit'), ('I', 'In-Person')], max_length=1, null=True)),
                ('should_notify_school_admin', models.BooleanField(default=False)),
                ('success_score', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('things_learned', models.TextField(blank=True, null=True)),
                ('how_better', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckInsFormText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('success_score_text', models.TextField(blank=True, null=True)),
                ('things_learned_text', models.TextField(blank=True, null=True)),
                ('how_better_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('student_id', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('Grade', models.CharField(blank=True, choices=[('PK', 'Pre-Kindergarten'), ('K', 'Kindergarten'), ('1', '1st Grade'), ('2', '2nd Grade'), ('3', '3rd Grade'), ('4', '4th Grade'), ('5', '5th Grade'), ('6', '6th Grade'), ('7', '7th Grade'), ('8', '8th Grade'), ('9', '9th Grade'), ('10', '10th Grade'), ('11', '11th Grade'), ('12', '12th Grade'), ('O', 'Other')], max_length=2, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='group',
            name='email_root',
        ),
        migrations.RemoveField(
            model_name='group',
            name='is_district',
        ),
        migrations.RemoveField(
            model_name='group',
            name='is_school',
        ),
        migrations.RemoveField(
            model_name='userah',
            name='name',
        ),
        migrations.AddField(
            model_name='group',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='email_contact',
            field=models.EmailField(default='test', max_length=255, verbose_name='email contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userah',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userah',
            name='first_name',
            field=models.CharField(default='Joe', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userah',
            name='last_name',
            field=models.CharField(default='Smith', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.School'),
        ),
        migrations.AddField(
            model_name='student',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Team'),
        ),
        migrations.AddField(
            model_name='checkinsformtext',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group'),
        ),
        migrations.AddField(
            model_name='checkins',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student'),
        ),
        migrations.AddField(
            model_name='checkins',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student'),
        ),
    ]
