# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-05 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170805_1649'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckIns',
            new_name='CheckIn',
        ),
        migrations.RenameModel(
            old_name='CheckInsFormText',
            new_name='CheckInFormText',
        ),
    ]
