# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-05 20:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170805_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 5, 20, 8, 41, 246290)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 5, 20, 8, 50, 974471)),
            preserve_default=False,
        ),
    ]
