# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-05 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170805_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
